INSERT INTO dbo.Search (searchString) VALUES ('Testing')
INSERT INTO dbo.Search (searchString) VALUES ('abcd')

INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('ABC Shop', '12345678', 'test@email.com', 'Cheapest Price', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('XYZ Shop', '12345678', 'test@email.com', 'Hello', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('123 Shop', '12345678', 'test@email.com', 'PinPoint', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('789 Shop', '12345678', 'test@email.com', '', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Testing Shop', '12345678', 'test@email.com', 'Lazy', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Wei Rong Shop', '12345678', 'test@email.com', '.....', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Nixon Shop', '12345678', 'test@email.com', '....', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Bryan Shop', '12345678', 'test@email.com', 'Blank', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('New Shop', '12345678', 'test@email.com', 'Food', 'Hougang', 'Hougang Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('ABC Shop', '12345678', 'test@email.com', 'Cheapest Price', 'Kovan', 'Kovan Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('XYZ Shop', '12345678', 'test@email.com', 'Hello', 'Ang Mo Kio', 'Ang Mo Kio Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('123 Shop', '12345678', 'test@email.com', 'PinPoint', 'Serangoon', 'Serangoon Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('789 Shop', '12345678', 'test@email.com', '', 'Ang Mo Kio', 'Ang Mo Kio Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Testing Shop', '12345678', 'test@email.com', 'Lazy', 'Ang Mo Kio', 'Ang Mo Kio Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Wei Rong Shop', '12345678', 'test@email.com', '.....', 'Woodland', 'Woodland Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Nixon Shop', '12345678', 'test@email.com', '....', 'Woodland', 'Woodland Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('Bryan Shop', '12345678', 'test@email.com', 'Blank', 'Yishun', 'Yishun Ave 1')
INSERT INTO dbo.Branch (shopName, phoneNumber, email, description, branchLocation, branchAddress) VALUES ('New Shop', '12345678', 'test@email.com', 'Food', 'Yishun', 'Yishun Ave 1')